spring.application.name=webhook-dispatcher
server.port=8082

spring.kafka.bootstrap-servers=localhost:9093
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.acks=all

spring.data.mongodb.uri=mongodb://localhost:27017/herald

management.endpoints.web.exposure.include=health,metrics,prometheus

herald.endpoint-service.url=http://localhost:8081
herald.retry.max-attempts=5
herald.retry.backoff-base-ms=10000