spring.application.name=endpoint-service
server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/herald
spring.datasource.username=herald
spring.datasource.password=herald
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
